---
title: 'Revised code for potential submission'
author: "Sofi Sinozich & Rachael Jackson"
date: "12/8/2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
library(tidyverse)
library(magrittr)
library(kableExtra)
library(scales)
library(glmnet)
library(glmnetUtils)
library(selectiveInference)
library(car)
library(lmtest)
library(fastDummies)
```

```{r echo=FALSE}
full_data <- readRDS("data/full_data.rds")
```

# Descriptives

```{r}
examiner_chart<-full_data %>% filter(!is.na(health_status2evg) & !is.na(examiner_id)) %>% group_by(examiner_id) %>% count(health_status2evg) %>% 
  ggplot + geom_bar(aes(x = health_status2evg,y=n,fill=ifelse(health_status2evg==1,"Excellent/Very Good","Good/Fair/Poor")),stat="identity") + 
  geom_label(aes(x=health_status2evg,y=n+500,label=n,
                 vjust=case_when(examiner_id==3007 & health_status2evg==1 ~ 1.25,
                                 n < 500 ~ .5,
                                 TRUE ~ 1)),
             size=3) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  labs(fill = "Status",
       x="",y="Patients Evaluated") +
  theme_light() +
  theme(legend.position="top",
        legend.title = element_text(size = 8, face="bold"),
        legend.text = element_text(size = 8),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  guides(fill = guide_legend(override.aes = list(size=5))) +
  facet_wrap(.~examiner_id) +
  ggtitle("Patients' Physician-Rated Health Status by Examining Physician")

# Health status overall
full_data %>% filter(!is.na(health_status) & !is.na(examiner_id)) %>% count(health_status) %>% 
  ggplot +
  geom_bar(aes(x = health_status,y=n),stat="identity") +
  theme_light() +
  theme(legend.position="none")+
  labs(x="Health Status",y="Patients Evaluated") +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 7000)) +
  scale_x_continuous(breaks=1:5,labels=c("Excellent","Very Good","Good","Fair","Poor")) +
  geom_label(aes(x=health_status,y=n,label=n)) +
  ggtitle("Patients' Physician-Rated Health Status")

# Physicians x referral status

```

```{r}
# Descriptive tables

# full_data %>% filter(!is.na(health_status2evg) & !is.na(examiner_id)) %>% 
#   mutate(health_statusex = ifelse(health_status2evg==1,"Excellent/very good","Good/fair/poor")) %>% 
#                        select(health_statusex,race,gender,age,region) %>% mutate_at(vars(-age),as.factor) %>% summary()

# Make table section

make_t1<-function(var) {
  full_data %>% 
  filter(!is.na(health_status2evg) & !is.na(examiner_id)) %>% 
  group_by(examiner_id) %>% count(!!sym(var)) %>% mutate(n=n/sum(n)) %>%
  group_by(!!sym(var)) %>% summarize(Mean = mean(n), Median = median(n), Max = max(n), Min = min(n)) %>% 
  rename(var=!!sym(var)) %>% mutate(var = as.character(var))
}

table1<-bind_rows(
    # Health status
    full_data %>% 
        filter(!is.na(health_status) & !is.na(examiner_id)) %>% 
        group_by(examiner_id) %>% count(health_status) %>% mutate(n=n/sum(n)) %>%
        group_by(health_status) %>% summarize(Mean = mean(n), Median = median(n), Max = max(n), Min = min(n)) %>% mutate(health_status = c("Excellent","Very Good","Good","Fair","Poor")) %>% rename(var=health_status),
    make_t1("gender"),
    make_t1("race"),
    make_t1("region")
) %>% mutate_at(vars(Mean:Min),~percent(.,accuracy=.1)) %>% 
  bind_rows(
    c(var="",Mean="",Median="",Max="",Min=""),
full_data %>% 
    filter(!is.na(health_status) & !is.na(examiner_id)) %>% 
    group_by(examiner_id) %>% summarize(n=median(age)) %>% summarize(Mean = mean(n), Median = median(n), Max = max(n), Min = min(n))  %>%  mutate_all(~round(.,1)) %>%  bind_cols(var = "Median Age") %>% select(var,everything()) %>% transmute_all(as.character)
  )

table1 %>% 
  kbl(format="latex",col.names = c("",names(table1)[-1]),caption="Summary Statistics Across Examiners")%>% 
  pack_rows(index=c("Health Status"=5,
                                       "Gender"=2,
                                       "Race"=4,
                                       "Region"=4)) 
```



# Regularization

```{r}
health_lasso_mat <- model.matrix(health_status2evg ~
                 race+ gender + scale(age) + region + time_of_day +
                 scale(systolic_bp) + scale(diastolic_bp) +
                 locomotion + paralysis + impairment + infection +
                 scale(bmi) + scale(weight) + scale(height)+ 
                 scale(rbc_count) + scale(wbc_count) + scale(plt_count) + scale(hemoglobin) +
                 hypertension + scale(waist_to_hip) + chest + heart +
                 examiner_id_factor + examiner_id_factor:gender + examiner_id_factor:white,data=full_data)

health_lasso_out <- model.frame(health_status2evg ~
                 race+ gender + scale(age) + region + time_of_day +
                 scale(systolic_bp) + scale(diastolic_bp) +
                 locomotion + paralysis + impairment + infection +
                 scale(bmi) + scale(weight) + scale(height)+ 
                 scale(rbc_count) + scale(wbc_count) + scale(plt_count) + scale(hemoglobin) +
                 hypertension + scale(waist_to_hip) + chest + heart +
                 examiner_id_factor + examiner_id_factor:gender + examiner_id_factor:white,data=full_data)$health_status2evg


health_lasso_mat_no3002 <- model.matrix(health_status2evg ~
                 race+ gender + scale(age) + region + time_of_day +
                 scale(systolic_bp) + scale(diastolic_bp) +
                 locomotion + paralysis + impairment + infection +
                 scale(bmi) + scale(weight) + scale(height)+ 
                 scale(rbc_count) + scale(wbc_count) + scale(plt_count) + scale(hemoglobin) +
                 hypertension + scale(waist_to_hip) + chest + heart +
                 examiner_id_factor + examiner_id_factor:gender + examiner_id_factor:white,data=full_data %>% filter(examiner_id != 3002) %>% mutate(examiner_id_factor = droplevels(examiner_id_factor)))

health_lasso_out_no3002 <- model.frame(health_status2evg ~
                 race+ gender + scale(age) + region + time_of_day +
                 scale(systolic_bp) + scale(diastolic_bp) +
                 locomotion + paralysis + impairment + infection +
                 scale(bmi) + scale(weight) + scale(height)+ 
                 scale(rbc_count) + scale(wbc_count) + scale(plt_count) + scale(hemoglobin) +
                 hypertension + scale(waist_to_hip) + chest + heart +
                 examiner_id_factor + examiner_id_factor:gender + examiner_id_factor:white,data=full_data%>% filter(examiner_id != 3002) %>% mutate(examiner_id_factor = droplevels(examiner_id_factor)))$health_status2evg

health_lasso <- cv.glmnet(health_status2evg ~
                            race+ gender + scale(age) + region + time_of_day +
                            scale(systolic_bp) + scale(diastolic_bp) +
                            locomotion + paralysis + impairment + infection +
                            scale(bmi) + scale(weight) + scale(height)+ 
                            scale(rbc_count) + scale(wbc_count) + scale(plt_count) + scale(hemoglobin) +
                            hypertension + scale(waist_to_hip) + chest + heart +
                            examiner_id_factor + examiner_id_factor:gender + examiner_id_factor:white + examiner_id_factor:white:gender,
                          data=full_data,
                          family= binomial(link = "logit"))


health_lasso2 <- glmnet::cv.glmnet(x = health_lasso_mat_no3002[,-1],
                 y=health_lasso_out_no3002,
                 family=binomial(link="logit"))

health_lasso3 <- cv.glmnet(health_status2evg ~
                            race_Black +race_Hispanic + race_Other + gender_Male + scale(age) + region + time_of_day +
                            scale(systolic_bp) + scale(diastolic_bp) +
                            locomotion + paralysis + impairment + infection +
                            scale(bmi) + scale(weight) + scale(height)+ 
                            scale(rbc_count) + scale(wbc_count) + scale(plt_count) + scale(hemoglobin) +
                            hypertension + scale(waist_to_hip) + chest + heart +
                            examiner_id_factor+ examiner_id_factor:gender_Male+examiner_id_factor:race_Black+examiner_id_factor:race_Hispanic+examiner_id_factor:race_Other,
                          data=modeling_data,
                          family= binomial(link = "logit"))


coef(health_lasso,s="lambda.1se")
coef(health_lasso2,s="lambda.1se")


fixedLassoInf(y=health_lasso_out_no3002,
              x=health_lasso_mat_no3002[,-1],
              beta=coef(health_lasso2, s=health_lasso2$lambda.1se),
              lambda=health_lasso2$lambda.1se,family="binomial",tol.kkt=1)
```

# Modeling (not regularized)

```{r}
modeling_data <- full_data %>% dummy_cols(select_columns=c("examiner_id_factor","race","gender"),remove_most_frequent_dummy = TRUE) %>% filter(!is.na(examiner_id))
  
health_model <- glm(health_status2evg ~
                 race_Black + race_Hispanic + race_Other + gender_Male + age + region + time_of_day +
                 systolic_bp + diastolic_bp +
                 locomotion + paralysis + impairment + infection +
                 bmi+
                 rbc_count + wbc_count + plt_count + hemoglobin +
                 hypertension + waist_to_hip + chest + heart,
                 data=modeling_data,
                 family=binomial(link="logit"))


health_model_ex <- update(health_model,.~.+examiner_id_factor)
health_model_exgen <- update(health_model_ex,.~.+examiner_id_factor:gender_Male)
health_model_exrace <- update(health_model_ex,.~.+examiner_id_factor:race_Black+examiner_id_factor:race_Hispanic+examiner_id_factor:race_Other)
health_model_exgenrace <- update(health_model_ex,.~.+examiner_id_factor:gender_Male+examiner_id_factor:race_Black+examiner_id_factor:race_Hispanic+examiner_id_factor:race_Other)

anova(health_model,health_model_ex,health_model_exgen,health_model_exrace,health_model_exgenrace)
BIC(health_model,health_model_ex,health_model_exgen,health_model_exrace,health_model_exgenrace)
lrtest(health_model,health_model_ex)
lrtest(health_model_ex,health_model_exgen)
lrtest(health_model_ex,health_model_exrace)

lrtest(health_model,health_model_ex,health_model_exgen,health_model_exgenrace)

vif(health_model_exgenrace)
alias(health_model)
```


